### ISSUE TITLE
ElementsInTree should be sorted by name

### ISSUE THREAD

**Issue by mnoskov** [evolution-cms/evolution#887] opened 2018-11-08 11:52 UTC
DEV fresh version
<img src="https://monosnap.com/image/WOSnUq3HeO7KpfXFxVF7ZShy2Im3Gx.png">

**Comment by pmfx** [comment] 2018-11-09 10:01
Confirmed. Same for me. Looks like it is sorted by ID. It should be sorted by name.

**Comment by Nicola1971** [comment] 2018-11-10 13:13
![sort](https://user-images.githubusercontent.com/7342798/48301731-bf72f200-e4f2-11e8-970b-1f32ef47a6b7.png)

https://github.com/evolution-cms/evolution/commit/288a6f96b5de245b52fbc7807ee12ef0dc6d491b

**Comment by Nicola1971** [comment] 2018-11-10 13:13
please test

**Comment by mnoskov** [comment] 2018-11-10 19:39
All elements are sorted as necessary, except modules:

![2018-11-11_00-38-32](https://user-images.githubusercontent.com/8789957/48305307-3687a500-e54a-11e8-8b2d-c7936051ec84.png)

**Comment by Nicola1971** [comment] 2018-11-10 23:46
@mnoskov thanks. I will check and fix tomorrow

**Comment by Nicola1971** [comment] 2018-11-11 10:19
![screenshot-localhost-2018 11 11-11-18-41](https://user-images.githubusercontent.com/7342798/48311668-98282d80-e5a3-11e8-85ba-e1523de12310.png)

**Comment by Nicola1971** [comment] 2018-11-12 10:00
can we close this ticket?

**Comment by pmfx** [comment] 2018-12-11 12:19
EVO 1.4.7
Categories are not sorted by name ASC

**Comment by Nicola1971** [comment] 2018-12-11 12:30
partially fixed - need to fix modules category order

**Closed** 2019-01-04 15:57 UTC
Labels: Area/Packages, Type/Enhancement
