### ISSUE TITLE
Cannot save documents in backend anymore (Chrome)

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1059] opened 2019-04-14 16:07 UTC
> VM570 main.js:272 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/

Chrome version: Google Chrome is up to date, Version 73.0.3683.103 (Official Build) (64-bit)

Clicking "Save + Continue Editing" has no effect.

File **main.js** around the reported line 272 holds:

```
// check connection to server
evo.checkConnectionToServer = function() {
  var xhr = new (window.ActiveXObject || XMLHttpRequest)('Microsoft.XMLHTTP');

  xhr.open('GET', evo.urlCheckConnectionToServer + '?time=' + new Date().getTime(), false);
  try {
    xhr.send();
    return (xhr.status >= 200 && xhr.status < 300 || xhr.status === 304);
  } catch (error) {
    return false;
  }
};
```

<br>

Searching for the problem revealed: https://stackoverflow.com/q/24639335/1066234

**Comment by 64j** [comment] 2019-04-14 16:16
Duplicate of https://github.com/evolution-cms/evolution/issues/1058

**Closed by 64j** 2019-04-14 16:16 UTC

**Comment by q2apro** [comment] 2019-04-14 16:18
Can be deleted. Just realized that the "fix" in `footer.inc.php` was causing the problem!

https://github.com/evolution-cms/evolution/issues/1058#issuecomment-482812084
