### ISSUE TITLE
"Export Static HTML" Not Working with Friendly urls enabled"

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#481] opened 2018-01-29 12:50 UTC
I updated the Evo docs site that I still have on my localhost, to the latest version 1.4.0

I tried to back it up as static files, to possibly use it for the new docs that are to be built via GitHub

On export / backup / save (whatever you wish to call it) all I get is a ton of empty .html files

Note: I am not getting any errors via the PHP error log or in the Manager

Can someone else please give this a try, just to confirm whether or not its a bug or to see if it's just my localhost

Cheers

**Comment by Nicola1971** [comment] 2018-01-29 13:04
just tested  static export in 1.4.0 (final)  on a localhost site and on live site: works as expected

**Comment by modxuser** [comment] 2018-01-29 13:14
@Nicola1971 Thanks for that

Do we have a list of must have PHP extensions & settings required for Evo anywhere ?

**Comment by Nicola1971** [comment] 2018-01-29 13:17
@modxuser not yet https://github.com/evolution-cms/evolution/issues/441

**Comment by modxuser** [comment] 2018-01-29 13:21
Just found this: https://develop.modx.com/develop/evolution/requirements/

**Comment by Nicola1971** [comment] 2018-01-29 13:29
yes, need something like this.
Please post it in the #441 issue

Can we close this issue?

**Comment by modxuser** [comment] 2018-01-29 14:20
After reviewing the settings I tried all the sites I have on localhost, the results:

1.0.7 - Works
1.0.8 - Works
1.0.15 - Works
1.2 - Doesn't work
1.2.1 - Doesn't work
1.4 - Doesn't work

All sites using 1.2 and above don't work, they produce all pages but the only one that has anything in it is the hompage and that has the content commented out

Note, the comments have been added on export

**Comment by Deesen** [comment] 2018-01-29 14:33
For me on latest dev (almost 1.4) the demo-site gets exported as expected.

**Comment by Nicola1971** [comment] 2018-01-29 14:35
> For me on latest dev (almost 1.4) the demo-site gets exported as expected.

same for me

@modxuser  the localhost issue can depend from your local webserver settings or folder permissions

**Comment by modxuser** [comment] 2018-01-29 14:36
@Nicola1971 
True, but as already noted - some work, some don't and the same goes for live servers

**Comment by Nicola1971** [comment] 2018-01-29 14:37
maybe a different htaccess?

**Comment by modxuser** [comment] 2018-01-29 14:37
Nope :)

**Comment by Deesen** [comment] 2018-01-29 14:38
I have also used it on localhost, but with PHP 5.6. Maybe this is the reason?

**Comment by Nicola1971** [comment] 2018-01-29 14:39
@Deesen i tested on localhost (uWamp) with PHP 7.1.2

**Comment by modxuser** [comment] 2018-01-29 14:40
@Deesen 

OK, will check PHP versions, but I know that the live servers are running PHP 7x, which makes this a possible nogo :(

**Comment by Nicola1971** [comment] 2018-01-29 14:42
just tested my local evo1.2.2 and a live 1.2.2 both worked

**Comment by Deesen** [comment] 2018-01-29 14:47
Then the cause of this issue seems not to be a PHP-version.

**Comment by Nicola1971** [comment] 2018-01-30 00:40
Tried everything - no issue.
Last question/test
 language ? character encoding?

**Comment by modxuser** [comment] 2018-01-30 13:18
As this is not a 5 minute job, I will have to come back with results once I have updated all of the sites and servers - this may take a while, so please don't close this thread, as it's not yet resolved

**Comment by modxuser** [comment] 2018-02-08 14:16
UPDATE:

I have now updated my local server and can now choose between 3 PHP versions - I have tried all of them to no avail.

The problem persists - it also happens on a brand new install, so I get the feeling something in the local server isn't switched on / activated

I also found a solution to the problem with the content code being commented out - its the setting "Minify php code in site cache" - it doesn't clean properly

e.g

this chunk:

&lt;!-- ################### Start Main Content ################### --&gt;
[*content*]
&lt;!-- ################### End Main Content ################### --&gt;

results in this:

<!--
content blah blah blah

**Comment by Nicola1971** [comment] 2018-02-08 15:34
@modxuser 
I can't replicate this issue on any of my live sites (linux), but on my Windows localhost (uWamp) i noticed:

- Friendly urls disabled (99% of times i don't enable f.u. on localhost tasks) - Export Static Works
- Friendly urls enabled:  - **Export Static Fails**  all files are 0Kb and empty  - except **doc-not-found.html**

I did not found any difference (resource settings) between doc-not-found page and the rest of demo pages.

I don't know if is the same issue - can you check your Friendly urls settings?

**Comment by modxuser** [comment] 2018-02-08 15:45
@Nicola1971 

Yep - exactly the same

Deactivate FURLs and the pages are created and the file size is no-longer 0kb. But all the links are wrong

**Comment by Nicola1971** [comment] 2018-02-08 20:06
Tried again on a live site. Issue confirmed 
"Export Static HTML" Not Working with Friendly urls enabled"

**Comment by modxuser** [comment] 2018-02-08 21:23
Cool, good to know it's not my setup, but a bug :)

**Comment by Deesen** [comment] 2018-02-09 16:33
Yes I always have them activated, no matter if localhost or not. I cannot recreate this issue, No matter if FURLs activated or not, I have no 0-byte-files. All is there on my Windows localhost PHP 7.1.

**Comment by bossloper** [comment] 2018-02-09 16:46
I can recreate the issue on a production server. CENTOS 7.4 / PHP 5.6 and it does not seem to matter if FURLs are active or not.
Though I also have a 'default' install on the same server and the export works fine.
Might be specific to the setup/templates/plugins/snippets used?

**Comment by bossloper** [comment] 2018-02-09 18:19
duplicate issue here: https://github.com/evolution-cms/evolution/issues/379

**Comment by Deesen** [comment] 2018-02-09 19:27
Hmm after looking at the code maybe the reason is function [curl_get_contents()](https://github.com/evolution-cms/evolution/blob/develop/manager/includes/extenders/export.class.inc.php#L116) which returns an empty string? Maybe somebody wants to test if my changes to `manager/includes/extenders/export.class.inc.php` solves the issue?

[export.class.inc.zip](https://github.com/evolution-cms/evolution/files/1712179/export.class.inc.zip)

**Comment by modxuser** [comment] 2018-02-09 23:10
@Deesen 

Dennis, just tried your modified file on my localhost in the Evo Docs 1.4.0 install and all seems to work, but I will need to control all files before I can say it's 100%

For starters, great job :)

Time for bed though now :)

**Comment by modxuser** [comment] 2018-02-12 13:56
@Deesen 

Dennis - just an update, I have gone through all the files and it seems that all is OK :)

So maybe this could be a commit for the next release ?

Cheers + thanks again for your help

**Comment by Deesen** [comment] 2018-02-14 14:02
Very nice, but I have changed 2 lines so I ask myself if both are neccessary or if only one of them solves the issue. What I changed is setting true to false for "verifying SSL Host" (indicates being connected to the right server). Maybe CURL returns 0 bytes if for any reason (even on localhost?) it thinks it is not connected to the "right" server:

`curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);`

and

`curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);`

which results in following redirects. As it seemed to me with FURLs enabled, there are redirects and without this option FOLLOWLOCATION enabled, the curl-function will return 0 bytes by default. But I think the solution for this issue is FOLLOWLOCATION, not SSL_VERIFYHOST.

**Comment by modxuser** [comment] 2018-02-14 15:10
@Deesen 

Dennis, you are talking a language I don't understand - ROFL

I just changed this:

`curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);`

back to this

`curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);`

and it still works, at least on my local server

**Comment by Deesen** [comment] 2018-02-20 17:47
Very nice, thank you. Will add the fix then and close this issue.

**Closed** 2018-02-20 17:47 UTC
Labels: bug
